### ISSUE TITLE
Getting 404 error when the wrong username specified

### ISSUE THREAD

**Issue by victoriosam** [tommyblue/smugmug-backup#13]
When the keys or tokens are wrong, the 401 error is pretty intuitive, but the 404 threw me off, until I reread your instructions about username not being the username input when login in via the portal.

time="2020-08-28T17:06:18-07:00" level=info msg="Getting albums for user victorio.sam@gmail.com...\n"
time="2020-08-28T17:06:19-07:00" level=error msg="404 Not Found"
time="2020-08-28T17:06:19-07:00" level=error msg="404 Not Found"
time="2020-08-28T17:06:19-07:00" level=error msg="404 Not Found"
time="2020-08-28T17:06:19-07:00" level=info msg="Found 0 albums\n"
time="2020-08-28T17:06:19-07:00" level=info msg="Backup completed."

Loved the tool! the dockerization made the installation a breeze!

Thanks for the wonderful tool.

**Comment by tommyblue** [comment]
yes, it's not really intuitive. I could make a first call to check if the credentials are correct. Let me take a look for a good endpoint to check it...
