### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by dshanske** [tommyblue/smugmug-backup#27]
I'm getting this despite having an API key and user key, and they all seem to be correct. What is the proper way to troubleshoot this? The output doesn't advise me of what isn't authorized.

**Comment by tommyblue** [comment]
I've noticed the same lately but I didn't have time to investigate yet. Though it seems to be related to metadata calls. Try setting `use_metadata_times=false` in the configuration file and let me know if it resolves the issue

**Comment by dshanske** [comment]
It seems to be generated fewer errors.
