### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by esullano** [tommyblue/smugmug-backup#3]
Hi Tommy, 
Thanks for putting this program together, this is awesome!  I'm running into this issue below, wondering if you have any ideas?

Getting albums for user esullano...
401 Unauthorized
401 Unauthorized
401 Unauthorized
2019/12/16 09:03:14 https://api.smugmug.com: reading response
[ERR] invalid character '<' looking for beginning of value
2019/12/16 09:03:15 https://api.smugmug.com: reading response
[ERR] invalid character '<' looking for beginning of value
2019/12/16 09:03:16 https://api.smugmug.com: reading response
[ERR] invalid character '<' looking for beginning of value
Found 0 albums

**Comment by 3zzy** [comment]
Same :(

**Comment by sfeakes** [comment]
I get exactly the same error.

**Comment by tommyblue** [comment]
It seems an authentication problem, did you all follow the instructions in the README under the Credentials paragraph?
The ` invalid character '<' looking for beginning of value` error is probably a json decode error, but it's not the main problem here. Authentication is failing (see 401s). 
Let me know if the procedure in the credentials paragraph was correctly followed, then I'll go on with the investigation.
Thanks! 😄

**Comment by tommyblue** [comment]
To verify you have the correct environment variables, run `export` and verify `USER_SECRET`, `USER_TOKEN`, `API_KEY` and `API_SECRET` are included in the printed list, with correct values

**Comment by sfeakes** [comment]
Yes all correct.   All I really wanted was an easy way to download all the content from SmugMug, so I simply modified that python script that's used to get the access_token and access_secret.  Added code to that was easier that finding the bug with go code.  But I *think* it's within your oath.go file I seem to remember the header generation part of the code.

**Comment by tommyblue** [comment]
Any chance you can share the python code you patched?

**Comment by bradr3d** [comment]
hey @sfeakes any chance you could share the patch
