### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by danodemano** [tommyblue/smugmug-backup#33]
Sorry for raising an "issue" but I couldn't find another way to reach out. This tool has done what I looked forever to do, mirror my SmugMug account to my NAS. So yeah, this is just here to say thank you and I really appreciate you putting this awesome project out there! I hope you have a fantastic holiday season!!

**Comment by tommyblue** [comment]
ehi @danodemano, that's awesome! 😃 
Thank you, very appreciated
