### ISSUE TITLE
Error trying to run the app on Windows

### ISSUE THREAD

**Issue by fscheps** [tommyblue/smugmug-backup#34]
Hi there, I´ve been looking for a tool to sync all SmugMug on my computer with all the respective folders, albums structure and without having to do it manually.
I think I configured ir correctly, but I cannot run the app on Windows. I tried executing from Windows Explorer, or from an elevated command prompt, but I always get the same error. I also tried different compatibility modes but no luck. Running Windows 10 here.

Thanks for your help!

![image](https://user-images.githubusercontent.com/48051505/206895822-b545ecbb-c052-437d-8b55-0386607301c9.png)

**Comment by tommyblue** [comment]
@fscheps I cannot reproduce. I'm trying the 64bit version and my windows is windows 10 pro 64.
Are you using 32 or 64 bit version? I'm running the tool from the command prompt, without admin permissions.
Moreover, could that error be caused by some windows "security" tool? I generally don't use them

**Comment by fscheps** [comment]
Hi there, I was using Windows 10 Pro 64. Now I have upgraded to Windows 11: Microsoft Windows [Version 10.0.22621.819].

Same error unfortunately :/ 

Thanks a lot for your help!

**Comment by tommyblue** [comment]
@fscheps could you try what's suggested here?

- https://answers.microsoft.com/en-us/windows/forum/all/this-app-cant-run-on-your-pc/f94db755-9416-470a-9532-de9dc6ec53d2
- https://www.makeuseof.com/how-to-fix-the-this-app-cant-run-on-your-pc-error-in-windows-10/

first thing to check: are you using the correct 32/64 bit version, according to your o.s. version?

**Comment by fscheps** [comment]
Hi @tommyblue  thank you thats what I meant when I mentioned I tried "different compatbility modes".

I am using Windows 11 Pro 64 bits

![image](https://user-images.githubusercontent.com/48051505/207290251-11162285-e65f-4103-a6db-8155c7f845f8.png)

Thanks a lot for your help 😉

**Comment by fscheps** [comment]
Hi @tommyblue  hehehe 😃 its fine to ask, eveyone can make mistakes 😃

Yes, I downloaded the package you mention for 64 bits.

Let me turn the question around, could it have been that the wrong version might have been packaged on that file?

**Comment by fscheps** [comment]
Very strange, I also dont have all the Firewall and all that enabled, not sure if I am missing something. I even exited Malwarebytes antivirus just in case, still doesnt work.
I also tried enabling Developer mode in Windows that should let me run unsigned EXE files but still the same error.
I am a bit lost here, not sure what else to try, if you or anyone has any tips they would be more than welcome. Thank you!

**Comment by fscheps** [comment]
Hi Tommy, did you have a chance to check this one? Thanks a lot for your help!

**Comment by fscheps** [comment]
@tommyblue  I tried to run the app in another Windows 11 laptop, same issue, unfortunately. Thanks for your help!

**Comment by tommyblue** [comment]
@fscheps no, sorry. It doesn't happen on my pc. I'm gonna use a virtual machine with a brand new installation (win11 64 bit). Let's see if I can reproduce

**Comment by tommyblue** [comment]
@fscheps I installed a fresh windows 11 on a virtual machine and I had no problems running the program. Honestly, I'm short in ideas here 😅

**Comment by fscheps** [comment]
Hi @tommyblue  I tried with a third virtual Windows 10, same issue unfortunatelly :(

**Comment by fscheps** [comment]
Hey @tommyblue Maybe I configured it wrong and that's why is failing? I am posting here how I configured it just in case I am missing something:

![image](https://user-images.githubusercontent.com/48051505/209660364-95fe2a69-bdc1-4af7-b1f7-728d6864da03.png)

Thanks for your help

**Comment by tommyblue** [comment]
@fscheps all seems correct. It's wonderful how it works on my side on a clean machine and it doesn't on your side. Must be a very tricky bug.
Please write me at `tommaso.visconti<>gmail.com` and let's arrange a video call, so maybe we can solve this
