### ISSUE TITLE
Overwrite file creation date with upload date

### ISSUE THREAD

**Issue by Uberpainer** [tommyblue/smugmug-backup#37]
Hi,

I have stumple upon your fine little app and it really works very good. I have a special need that I hope you might be able to help me solve or guide me in the right direction.

I have a album online at Smugmug that both my wife and I has contributed to. Issue is that for a year ago did timestamps sudden fuckup everything in th album so now the album is sorted by upload data.

My hope for help is to slightly modify you app to populate the file creation date to be replaced with the DateTimeUploaded value.

Can you maybe give me a hint on how i make this small change?

Regards
Anders Jensen

**Comment by tommyblue** [comment]
Hi @Uberpainer , sorry I'm so late with my reply 😓 
If I understand correctly, you want to change the file creation date in your disk, right? Currently the software uses [the `setChTime` function](https://github.com/tommyblue/smugmug-backup/blob/08f2244fc082048404bd7527eed9ffcdb62ff7db/api.go#L152C18-L164) to set the file mtime. The function tries with the `AlbumImage.DateTimeOriginal` field or calls the [`imageTimestamp`](https://github.com/tommyblue/smugmug-backup/blob/08f2244fc082048404bd7527eed9ffcdb62ff7db/api.go#L80-L86) function if the first attempt fails

To use the `AlbumImage.DateTimeUploaded` field, you should add the field to the [`albumImage` struct](https://github.com/tommyblue/smugmug-backup/blob/08f2244fc082048404bd7527eed9ffcdb62ff7db/json_structs.go#L76) (after `DateTimeOriginal`), then use it in the `setChTime`. Obviously you should not replace the default behaviour, so it could be a configurable option.

To do that, you should add the option to the [`Conf` struct](https://github.com/tommyblue/smugmug-backup/blob/08f2244fc082048404bd7527eed9ffcdb62ff7db/smugmug.go#L15). It could be something like `UseDateTimeUploadedTime`. It requires some coding here and there but you can use `UseMetadataTimes` as reference (it does a very similar thing).

Let me know if you want to give it a shot, I can help you with blocking points 😄
