### ISSUE TITLE
single apostrophe in filenames not saving properly

### ISSUE THREAD

**Issue by turnkit** [tommyblue/smugmug-backup#38]
What a God-send. Thanks so much for this app!

I am running it on Windows 11 under WSL2 Ubuntu,

With a filename on smugmug such as:

> Bob's children

the resultant downloaded file is:

> Bob&#39;s children

edit: okay this funny -- the github issues text editor converts the output so it's hard to show.  The problem is that it shows up in the Windows file system as:
> B o b & # 3 9 ; s    c h i l d r e n

But remove the spaces.

Not sure if this is due to using WSL2 or not but ideally single apostrophe's would come over correctly. Probably many unicode issue? Not sure what's happening but this is a simple example where the filename gets harder to read when using the program.

Thanks again.

**Comment by tommyblue** [comment]
Hi @turnkit
just giving a look, I need to perform some tests to understand if it works on Linux or the issue affects all the operating systems.
Whatever the result of the tests, I think the patch is required in the [`*albumImage.buildFilename`](https://github.com/tommyblue/smugmug-backup/blob/main/json_structs.go#L109) function.

**Comment by tommyblue** [comment]
@turnkit I finally found some time to investigate, and fix, the issue. [v1.5.1](https://github.com/tommyblue/smugmug-backup/releases/tag/v1.5.1) is the fixed version, please give it a try.
Thanks for reporting the issue!
