### ISSUE TITLE
empty folder and gallery on smugmug leads to fatal error

### ISSUE THREAD

**Issue by turnkit** [tommyblue/smugmug-backup#39]
Not a big deal but on SmugMug I had a folder and in that folder just an empty gallery.

When I attempted to backup everything I got this error:

ERRO[0031] cannot get album images for /api/v2/album/RJ84f9!images  error="cannot build image filename: empty resulting name"

Ideally the empty folder and gallery would be created on the local file system and no error would be thrown.

If it's too difficult then a clearer, more descriptive, error would be an improvement.  The meaning of the error given took me a while to track down.

**Comment by turnkit** [comment]
edit: actually this ERRO turned out to be a much bigger deal as until I deleted the empty folders on smugmug I couldn't complete the backup.

Once I deleted the empty folders I re-ran the backup and there were many more images downloading still.

So it would be good to fix as otherwise people might accidently not get all their images.

**Comment by turnkit** [comment]
Even though I deleted the folder that only contained an empty gallery I still get the ERRO[0031] but with only the follow error code I cannot track down what the issue is, where any empty folder or name might be.

> ERRO[0031] cannot get album images for /api/v2/album/RJ84f9!images  error="cannot build image filename: empty resulting name"

**Comment by turnkit** [comment]
Is it possible to use the API to get a total number of photos for each folder and each gallery for a debug mode -- such that I could track down the problematic folder or files?

**Comment by turnkit** [comment]
![image](https://github.com/tommyblue/smugmug-backup/assets/4126167/bd751d4d-c605-4440-ab4f-ab729fdcffad)

I found a gallery with two pictures with the same filename.  Could this be causing the fatal error?

Since SmugMug wouldn't let me rename the filename I manually download one of the images with a duplicate filename and then deleted it from the gallery and then re-rain the backup.

[BTW having the ability to resume downloads like this is such a great feature.]

I re-ran but still got the same errors:
ERRO[0031] cannot get album images for /api/v2/album/RJ84f9!images  error="cannot build image filename: empty resulting name"
...
FATA[0236] completed with 1 errors, please check logs

**Comment by turnkit** [comment]
Finally found the issue.  There was a folder called SmugShots which was from an app on my iPhone 3 or so.  

Apparently there was an app that would let me upload photos directly to smugmug but all the photos in that folder had no file name.  When I right click to download it would show x.jpg for all of them. 

I manually downloaded those images and deleted the folder and the FATA (fatal) error stopped.

Perhaps if you have a empty filename instead of erroring out you could just generate a made up filename to prevent the problem of aborted backups.

![image](https://github.com/tommyblue/smugmug-backup/assets/4126167/7cef7192-73a6-45ef-9047-b7c1f70da49d)

**Comment by turnkit** [comment]
ref: https://don.blogs.smugmug.com/2008/07/10/smugshot-for-iphone-shoot-geotag-and-upload/

**Comment by tommyblue** [comment]
@turnkit thanks for the deep investigation. I find a first issue, caused by the fact that the Smugmug API, in case of empty folder, doesn't return an empty list of images for the album but completely skip the "AlbumImage" attribute in the JSON response 🤯 
I'm gonna fix the code to skip empty albums

**Comment by tommyblue** [comment]
@turnkit should be resolved in v1.4.0
