### ISSUE TITLE
Handling of two files in the same folder with the same name

### ISSUE THREAD

**Issue by michaeljmuller** [tommyblue/smugmug-backup#41]
Great program; thanks for making it available!

I noticed that some of my images keep getting downloaded over and over.

It turns out this is because they were duplicates in SmugMug, which apparently allows you to have two files in the same folder with the same name.  The metadata is slightly different in the two folders, which results in different file sizes.  

The downloader behavior is strange, it seems to alternate between downloading first one, then the other of the two duplicate files.

I'll address this by using my logs to locate my duplicate photos and then remove them, but I thought you might want to add code to handle this situation.

Thanks again!

**Comment by michaeljmuller** [comment]
It turns out this is a slightly bigger problem than I thought.  It turns out that there are some images that are NOT duplicates but that have the same filename.  I don't see any way in SmugMug to rename the file, and I don't want to delete one of them.

**Comment by michaeljmuller** [comment]
I was able to mitigate the problem by pre-pending the "image key" to the filename. 

Strangely, this did not resolve the problem entirely; I still have about 80 files that re-download with each execution (down from 700-1000).

**Comment by michaeljmuller** [comment]
More detail:

I have two files named "cominghome.JPG" in a folder (gallery).  They're different files (one is color, the other is greyscale).  

One file has image key G4fgPGc and the other has image key 4RwqKND.  

On first execution, both files download.  On each subsequent execution, the  image with key G4fgPGc downloads again.

**Comment by michaeljmuller** [comment]
I think this may be a SmugMug problem.  

I went into the API browser and pulled up the AlbumImage for an item that gets consistently re-downloaded.  When I use the browser to download the image from the "ArchivedURI", my file size and checksum do not match the ArchivedMD5 and ArchivedSize that SmugMug lists for that item.

**Comment by tommyblue** [comment]
Hi @michaeljmuller, thanks for your investigation! I also noticed that my backup keeps downloading the same files and I'm pretty sure you're right: the reason is the size doesn't match. I don't know the reason though. It could be an issue in SmugMug or, for some reason, their calculation isn't the same we do. Not sure of the reason but could be something involving the file system.

Did you try (or, could you try) to re-upload one of those images and check if their size changes in Smugmug? Just to check whether it was a momentary issue or it's constantly wrong

**Comment by michaeljmuller** [comment]
I submitted a ticket with SmugMug.  I'll update here if I hear back from them.

If I don't hear back from them, I'll try your suggestion of re-uploading the "broken" files.

Thanks @tommyblue !

**Comment by michaeljmuller** [comment]
SmugMug has acknowledged that this is a bug.  They'll let me know when the problem has been corrected.  I'll update here when I hear back from SmugMug.

**Comment by Jefpix** [comment]
I just started using smugmug backup and it took nearly 3 days to download my nearly 4 TB of files. Now that I've added a couple more files today to Smugmug, I re-ran SmugmugBackup, and it seems to be re-downloading everything. I've looked at some of the folders where it purports to be downloading, and the file count never increases. It seems to merely be downloading the same files on top of the ones already downloaded. Here is my toml file: 
[authentication]
api_key = "hidden"
api_secret = "hidden"
user_token = "hidden"
user_secret = "hidden"

[store]
destination = "I:/SmugmugBackup"
file_names = "{{.FileName}}"
use_metadata_times = true
force_metadata_times = true
write_csv = true
force_video_download = true
concurrent_albums = 5
concurrent_downloads = 10

Am I missing a parameter?
Jeff
