### ISSUE TITLE
Backup of raw images

### ISSUE THREAD

**Issue by varun729** [tommyblue/smugmug-backup#44]
The application works great with downloading all albums, but I have some images in both the RAW and JPG format. In most cases I see that the JPG was downloaded, and in only a few instances the RAW image was downloaded. Can we add support to download both the RAW and JPG, which will give me a true backup.

**Comment by tommyblue** [comment]
Well, yes we could. But I don't have raw support in my account so I don't really know how to learn how to do it. Maybe you can help sending some info about how raw images are treated in the api?
