### ISSUE TITLE
No window opens on Windows

### ISSUE THREAD

**Issue by jcrookwa** [tommyblue/smugmug-backup#46]
When attempting to run this on windows, after clicking the executable nothing appears to happen. It looks like a window tries to open for a second and then immediately closes. I'm not sure what I'm doing wrong but no download occurs. Any ideas?

![image](https://github.com/tommyblue/smugmug-backup/assets/73679140/5e9b891b-ee33-42e4-b5e5-b5f5696207e7)
Thanks!

**Comment by tommyblue** [comment]
I think something could be wrong in the configuration. Can you please run the program from the terminal? In this way the console remains opened and you can see the error message

**Comment by jcrookwa** [comment]
When I run this, I immediately get this error:
`time="2023-10-24T13:13:53+08:00" level=fatal msg="Configuration error" error="While parsing config: toml: invalid escaped character U+0042 'B'"`

**Comment by jcrookwa** [comment]
The current config is:
`[authentication]
api_key = "whttkh<withdrawn>"
api_secret = "wrnMQTr<withdrawn>"
user_token = "hzGRs<withdrawn>"
user_secret = "m7K3h8<withdrawn>"

[store]
destination = "Z:\Backup"
file_names = "{{.FileName}}"
use_metadata_times = true
force_metadata_times = true
write_csv = true
force_video_download = true
concurrent_albums = 5
concurrent_downloads = 10
`

**Comment by tommyblue** [comment]
It's the destination. Check the readme. It should be double slashed Z:\\Backup
