### ISSUE TITLE
SmugmugBackup works perfectly! Thank you.

### ISSUE THREAD

**Issue by Jefpix** [tommyblue/smugmug-backup#47]
Never mind. :) The program worked perfectly well! Thank you for creating it!

**Comment by Jefpix** [comment]
P.S. My csv file only has 19091 lines. My smugmug account has 295,000 files...

**Comment by Jefpix** [comment]
P.P.S. this program is fantastic! Thank you for creating it.

**Comment by tommyblue** [comment]
😄  thanks man

**Comment by Jefpix** [comment]
How can I send you a donation for smugmugbackup? I have Venmo, PayPal, and facebook payment methods.

 

Jeff

 

Jeff Hall Photography

925 Wild Dunes Circle

Wilmington, NC 28411

603-801-6440

***@***.***

**Comment by tommyblue** [comment]
wow, thanks for that man 😄 
my paypal address is tommaso.visconti@gmail.com
🖖🏼
