### ISSUE TITLE
simplify oauth token retrieval instructions

### ISSUE THREAD

**Issue by dsporter** [tommyblue/smugmug-backup#8]
You can find an oauth access token for your account on the privacy tab of account settings on smugmug.

It's not necessary to run code or use your web app to get a token.

<img width="987" alt="smugmug-oauth-token" src="https://user-images.githubusercontent.com/126949/89113754-d4f82000-d429-11ea-83a3-7ea862d29683.png">

**Comment by tommyblue** [comment]
<img src="https://media.giphy.com/media/Um3ljJl8jrnHy/giphy.gif" />

**Comment by tommyblue** [comment]
Thanks @dsporter that was illuminating 😄
